package com.jbravo.pokegotchi.app.motor.tienda;

public class ListadoPokemons{

    public static String Pokemon(int Opcion){ //Muestra el aspecto de la mascota
        switch (Opcion){
            case 1: return  "/Sprites/001.png" + "-Bulbasaur";
            case 2: return  "/Sprites/002.png" + "-Ivysaur";
            case 3: return  "/Sprites/003.png" + "-Venusaur";
            case 4: return  "/Sprites/004.png" + "-Charmander";
            case 5: return  "/Sprites/005.png" + "-Charmeleon";
            case 6: return  "/Sprites/006.png" + "-Charizard";
            case 7: return  "/Sprites/007.png" + "-Squirtle";
            case 8: return  "/Sprites/008.png" + "-Wartortle";
            case 9: return  "/Sprites/009.png" + "-Blastoise";
            case 10: return "/Sprites/010.png" + "-Caterpie";
            case 11: return "/Sprites/011.png" + "-Metapod";
            case 12: return "/Sprites/012.png" + "-Butterfree";
            case 13: return "/Sprites/013.png" + "-Weedle";
            case 14: return "/Sprites/014.png" + "-Kakuna";
            case 15: return "/Sprites/015.png" + "-Beedrill";
            case 16: return "/Sprites/016.png" + "-Pidgey";
            case 17: return "/Sprites/017.png" + "-Pidgeotto";
            case 18: return "/Sprites/018.png" + "-Pidgeor";
            case 19: return "/Sprites/019.png" + "-Rattata";
            case 20: return "/Sprites/020.png" + "-Raticate";
            case 21: return "/Sprites/021.png" + "-Spearow";
            case 22: return "/Sprites/022.png" + "-Fearow";
            case 23: return "/Sprites/023.png" + "-Ekans";

            case 24: return "/Sprites/024.png" + "-Arbok";
            case 25: return "/Sprites/025.png" + "-Pikachu";
            case 26: return "/Sprites/026.png" + "-Raichu";
            case 27: return "/Sprites/027.png" + "-Sandshrew";
            case 28: return "/Sprites/028.png" + "-Sandslash";
            case 29: return "/Sprites/029.png" + "-Nidoran";
            case 30: return "/Sprites/030.png" + "-Nidorina";
            case 31: return "/Sprites/031.png" + "-Nidoqueen";
            case 32: return "/Sprites/032.png" + "-Nidoran";
            case 33: return "/Sprites/033.png" + "-Nidorino";
            case 34: return "/Sprites/034.png" + "-Nidoking";
            case 35: return "/Sprites/035.png" + "-Clefairy";
            case 36: return "/Sprites/036.png" + "-Clefable";
            case 37: return "/Sprites/037.png" + "-Vulpix";
            case 38: return "/Sprites/038.png" + "-Ninetales";
            case 39: return "/Sprites/039.png" + "-Jigglypuff";
            case 40: return "/Sprites/040.png" + "-Wigglytuff";
            case 41: return "/Sprites/041.png" + "-Zubat";
            case 42: return "/Sprites/042.png" + "-Golbat";
            case 43: return "/Sprites/043.png" + "-Oddish";
            case 44: return "/Sprites/044.png" + "-Gloom";
            case 45: return "/Sprites/045.png" + "-Vileplume";
            case 46: return "/Sprites/046.png" + "-Paras";
            case 47: return "/Sprites/047.png" + "-Parasect";

            case 48: return "/Sprites/048.png" + "-Venonat";
            case 49: return "/Sprites/049.png" + "-Venomoth";
            case 50: return "/Sprites/050.png" + "-Diglett";
            case 51: return "/Sprites/051.png" + "-Dugtrio";
            case 52: return "/Sprites/052.png" + "-Meowth";
            case 53: return "/Sprites/053.png" + "-Persian";
            case 54: return "/Sprites/054.png" + "-Psyduck";
            case 55: return "/Sprites/055.png" + "-Golduck";
            case 56: return "/Sprites/056.png" + "-Mankey";
            case 57: return "/Sprites/057.png" + "-Primeape";
            case 58: return "/Sprites/058.png" + "-Growlithe";
            case 59: return "/Sprites/059.png" + "-Arcanine";
            case 60: return "/Sprites/060.png" + "-Poliwag";
            case 61: return "/Sprites/061.png" + "-Poliwhirl";
            case 62: return "/Sprites/062.png" + "-Poliwrath";
            case 63: return "/Sprites/063.png" + "-Abra";
            case 64: return "/Sprites/064.png" + "-Kadabra";
            case 65: return "/Sprites/065.png" + "-Alakazam";
            case 66: return "/Sprites/066.png" + "-Machop";
            case 67: return "/Sprites/067.png" + "-Machoke";
            case 68: return "/Sprites/068.png" + "-Machamp";
            case 69: return "/Sprites/069.png" + "-Bellsprout";
            case 70: return "/Sprites/070.png" + "-Weepinbell";
            case 71: return "/Sprites/071.png" + "-Victreebel";
            case 72: return "/Sprites/072.png" + "-Tentacool";
            case 73: return "/Sprites/073.png" + "-Tentacruel";

            case 74: return "/Sprites/074.png" + "-Geodude";
            case 75: return "/Sprites/075.png" + "-Graveler";
            case 76: return "/Sprites/076.png" + "-Golem";
            case 77: return "/Sprites/077.png" + "-Ponyta";
            case 78: return "/Sprites/078.png" + "-Rapidash";
            case 79: return "/Sprites/079.png" + "-Slowpoke";
            case 80: return "/Sprites/080.png" + "-Slowbro";
            case 81: return "/Sprites/081.png" + "-Magnemite";
            case 82: return "/Sprites/082.png" + "-Magneton";
            case 83: return "/Sprites/083.png" + "-Farfetch'd";
            case 84: return "/Sprites/084.png" + "-Doduo";
            case 85: return "/Sprites/085.png" + "-Dodrio";
            case 86: return "/Sprites/086.png" + "-Seel";
            case 87: return "/Sprites/087.png" + "-Dewgong";
            case 88: return "/Sprites/088.png" + "-Grimer";
            case 89: return "/Sprites/089.png" + "-Muk";
            case 90: return "/Sprites/090.png" + "-Shellder";
            case 91: return "/Sprites/091.png" + "-Cloyster";
            case 92: return "/Sprites/092.png" + "-Gastly";
            case 93: return "/Sprites/093.png" + "-Haunter";
            case 94: return "/Sprites/094.png" + "-Gengar";
            case 95: return "/Sprites/095.png" + "-Onix";
            case 96: return "/Sprites/096.png" + "-Drowzee";
            case 97: return "/Sprites/097.png" + "-Hypno";
            case 98: return "/Sprites/098.png" + "-Krabby";
            case 99: return "/Sprites/099.png" + "-Kingler";

            case 100: return "/Sprites/100.png" + "-Voltorb";
            case 101: return "/Sprites/101.png" + "-Electrode";
            case 102: return "/Sprites/102.png" + "-Exeggcute";
            case 103: return "/Sprites/103.png" + "-Exeggutor";
            case 104: return "/Sprites/104.png" + "-Cubone";
            case 105: return "/Sprites/105.png" + "-Marowak";
            case 106: return "/Sprites/106.png" + "-Hitmonlee";
            case 107: return "/Sprites/107.png" + "-Hitmonchan";
            case 108: return "/Sprites/108.png" + "-Lickitung";
            case 109: return "/Sprites/109.png" + "-Koffing";
            case 110: return "/Sprites/110.png" + "-Weezing";
            case 111: return "/Sprites/111.png" + "-Rhyhorn";
            case 112: return "/Sprites/112.png" + "-Rhydon";
            case 113: return "/Sprites/113.png" + "-Chansey";
            case 114: return "/Sprites/114.png" + "-Tangela";
            case 115: return "/Sprites/115.png" + "-Kangashan";
            case 116: return "/Sprites/116.png" + "-Horsea";
            case 117: return "/Sprites/117.png" + "-Seadra";
            case 118: return "/Sprites/118.png" + "-Goldeen";
            case 119: return "/Sprites/119.png" + "-Seaking";
            case 120: return "/Sprites/120.png" + "-Staryu";
            case 121: return "/Sprites/121.png" + "-Starmie";
            case 122: return "/Sprites/122.png" + "-Mr. Mime";
            case 123: return "/Sprites/123.png" + "-Scyther";
            case 124: return "/Sprites/124.png" + "-Jynx";
            case 125: return "/Sprites/125.png" + "-Electabuzz";

            case 126: return "/Sprites/126.png" + "-Magmar";
            case 127: return "/Sprites/127.png" + "-Pinsir";
            case 128: return "/Sprites/128.png" + "-Tauros";
            case 129: return "/Sprites/129.png" + "-Magikarp";
            case 130: return "/Sprites/130.png" + "-Gyarados";
            case 131: return "/Sprites/131.png" + "-Lapras";
            case 132: return "/Sprites/132.png" + "-Ditto";
            case 133: return "/Sprites/133.png" + "-Eevee";
            case 134: return "/Sprites/134.png" + "-Vaporeon";
            case 135: return "/Sprites/135.png" + "-Jolteon";
            case 136: return "/Sprites/136.png" + "-Flareon";
            case 137: return "/Sprites/137.png" + "-Porygon";
            case 138: return "/Sprites/138.png" + "-Omanyte";
            case 139: return "/Sprites/139.png" + "-Omastar";
            case 140: return "/Sprites/140.png" + "-Kabuto";
            case 141: return "/Sprites/141.png" + "-Kabutops";
            case 142: return "/Sprites/142.png" + "-Aerodacyl";
            case 143: return "/Sprites/143.png" + "-Snorlax";
            case 144: return "/Sprites/144.png" + "-Articuno";
            case 145: return "/Sprites/145.png" + "-Zapdos";
            case 146: return "/Sprites/146.png" + "-Moltres";
            case 147: return "/Sprites/147.png" + "-Dratini";
            case 148: return "/Sprites/148.png" + "-Dragonair";
            case 149: return "/Sprites/149.png" + "-Dragonite";
            case 150: return "/Sprites/150.png" + "-Mewtwo";
            case 151: return "/Sprites/151.png" + "-Mew";

            default: return "/icons/Vacio.png-Posicion inválida";
        }
    }
}
